Feat/#29 categories table
v-to-u/vitamin-to-u-backend pull request #31
Opened 2024-02-07 08:59 UTC by bigstone0

## 🚀 이슈 번호
- close #28 카테고리 테이블 구현

## 🫶 PR 내용
효능과 원재료, 각각의 매핑 테이블 구현

2024-02-07 13:44 UTC, tidavid1 requested changes

2024-02-07 13:44 UTC, kyungminnnnn commented on build.gradle
> +    runtimeOnly 'com.h2database:h2'
이거 중첩되서 지워도 될거 같습니다 :D

2024-02-07 13:44 UTC, kyungminnnnn commented on src/main/java/io/vtou/vitamintou/VitaminToUBackendApplication.java
> +import org.mybatis.spring.annotation.MapperScan;
필요없는 임포트인거같아요!

2024-02-07 13:44 UTC, kyungminnnnn commented on build.gradle
> +
삭제해주세여 :D

2024-02-07 13:44 UTC, kyungminnnnn commented on src/main/java/io/vtou/vitamintou/domain/supplements/domain/enums/SupplementsMaterial.java
> +    }
`@RequiredArgsConstructor` 사용해도 될거같아요

2024-02-07 13:44 UTC, kyungminnnnn commented on src/main/java/io/vtou/vitamintou/domain/supplements/domain/enums/SupplementsEfficiency.java
> +    }
`@RequiredArgsConstructor` 사용해도 될거같아요

2024-02-07 13:44 UTC, kyungminnnnn commented on src/main/java/io/vtou/vitamintou/domain/supplements/infrastructure/SupplementsJpaRepository.java
> +import org.springframework.data.jpa.repository.Query;
불필요한 임포트 삭제하기!

2024-02-07 13:44 UTC, kyungminnnnn commented on src/main/java/io/vtou/vitamintou/mapper/SupplementsMapper.java
> +    void insertSupplements(SupplementsCreateRequestDto supplementsCreateRequestDto,String efficiency);
??? 이거 어떤건지 설명해주세요!

2024-02-07 13:44 UTC, kyungminnnnn commented on src/main/java/io/vtou/vitamintou/domain/supplements/service/SupplementsService.java
> +
이거 왜 주석인지 설명해주세요!

2024-02-08 08:27 UTC, bigstone0 commented on src/main/java/io/vtou/vitamintou/mapper/SupplementsMapper.java
> +    void insertSupplements(SupplementsCreateRequestDto supplementsCreateRequestDto,String efficiency);
삭제 했습니다!!

2024-02-08 08:27 UTC, bigstone0 commented on src/main/java/io/vtou/vitamintou/domain/supplements/service/SupplementsService.java
> +
데이터 들어올때 효능하고 원재료 키워드 확인하는 코드인데 작동 잘 안돼서 일단 주석처리 했습니다

2024-02-10 02:22 UTC, tidavid1 approved these changes

2024-02-10 02:22 UTC, merged